In [2]:
pip install Numpy 


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import numpy as np 
data = np.random.randn(2,3)
data

array([[ 1.99679861,  1.20067934, -1.90228427],
       [ 2.1340671 ,  2.10758684,  0.96026382]])

In [4]:
data *10


array([[ 19.96798607,  12.00679336, -19.02284271],
       [ 21.34067101,  21.07586835,   9.60263817]])

In [5]:
data + data 

array([[ 3.99359721,  2.40135867, -3.80456854],
       [ 4.2681342 ,  4.21517367,  1.92052763]])

In [6]:
data.shape 

(2, 3)

In [7]:
data.dtype

dtype('float64')

In [8]:
data1 = [6, 7.5, 8, 9, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 9. , 1. ])

In [9]:
d2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(d2)
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.ndim


2

In [11]:
arr2.shape

(2, 4)

In [12]:
arr1.dtype

dtype('float64')

In [13]:
arr2.dtype

dtype('int64')

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.empty((2,3,2))

array([[[2.2677866e-316, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000]],

       [[0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000]]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
#type cast 
arr = np.array([1,2,3,4,5,6])
arr.dtype

dtype('int64')

In [19]:
floatarr=arr.astype(np.float64)
floatarr.dtype

dtype('float64')

In [20]:
a=np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a[5]


5

In [22]:
a[5:8]

array([5, 6, 7])

In [23]:
a[5:8]=12
a

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [24]:
a_slice = a[5:8]
a_slice

array([12, 12, 12])

In [25]:
a_slice[:]=30
a_slice

array([30, 30, 30])

In [26]:
a

array([ 0,  1,  2,  3,  4, 30, 30, 30,  8,  9])